# syntax=docker/dockerfile:1

# ============================================
# Stage 1: Dependencies
# ============================================
FROM node:20-alpine AS deps
WORKDIR /app

# Install dependencies needed for native modules
RUN apk add --no-cache libc6-compat

# Copy package files and npm config
COPY package.json package-lock.json* .npmrc* ./

# Install all dependencies (including dev for build)
RUN npm ci

# ============================================
# Stage 2: Builder
# ============================================
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set build environment
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Build the Next.js application (standalone mode)
RUN npm run build

# ============================================
# Stage 3: Production Runner (Web)
# ============================================
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy built standalone application
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]

# ============================================
# Stage 4: Worker Runner
# ============================================
FROM node:20-alpine AS worker
WORKDIR /app

ENV NODE_ENV=production

# Install tsx globally for running TypeScript
RUN npm install -g tsx

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 worker

# Copy package files and install production dependencies
COPY package.json package-lock.json* .npmrc* ./
RUN npm ci --omit=dev

# Copy source files needed for workers
COPY --from=builder /app/src ./src
COPY --from=builder /app/tsconfig.json ./

# Copy migration files (generated by drizzle-kit generate)
COPY --from=builder /app/drizzle ./drizzle

# Copy startup script
COPY deploy/start-worker.sh ./start-worker.sh

# Make startup script executable and fix permissions
RUN chmod +x ./start-worker.sh && \
    chown -R worker:nodejs /app

USER worker

CMD ["./start-worker.sh"]
